#!/bin/bash

# put this shell script into /usr/local/bin and type
# . cross
# before compiling a program with a cross-compiler

PREFIX=/opt/crossroot
ARCH=i586
TARGET=mingw32msvc
DEV_PREFIX=/usr/libexec/gcc/$ARCH-$TARGET

export CC="$ARCH-$TARGET-gcc -mms-bitfields -I/opt/crossroot/include "
export CXX="$ARCH-$TARGET-g++ -mms-bitfields"
export CFLAGS="-O2 -march=i586 -mms-bitfields"
export CXXFLAGS="-O2 -march=i586 -mms-bitfields"
export PKG_CONFIG_PATH=/opt/crossroot/lib/pkgconfig
export PATH="$PREFIX/bin:$PREFIX/$ARCH-$TARGET/bin:$PATH"
export LD_LIBRARY_PATH=$PREFIX/lib:/lib
export LDFLAGS="-L$PREFIX/lib"
export OBJDUMP=/usr/bin/$ARCH-$TARGET-objdump
export OBJCOPY=/usr/bin/$ARCH-$TARGET-objcopy
export RANLIB=/usr/bin/$ARCH-$TARGET-ranlib
export WINDRES=/usr/bin/$ARCH-$TARGET-windres
export HOST_CC=/usr/bin/gcc

