#!/bin/bash


export CC=
export CXX=
export CFLAGS=
export PKG_CONFIG_PATH=
export LD_LIBRARY_PATH=
export LDFLAGS=
export OBJDUMP=
export OBJCOPY=
export RANLIB=
export WINDRES=
export HOST_CC=
export DEV_PATH=

. /etc/profile
